"""
Quantum circuit export (OpenQASM 2.0) for QFT and unitary seeds.

Provides `export_qft_qasm` and `export_unitary_seed_qasm` to generate
quantum circuits from butterfly transforms.
"""

from __future__ import annotations

import numpy as np

from .config import DEFAULT_TOL


def export_qft_qasm(n_qubits: int, include_swaps: bool = True) -> str:
    """
    Generate OpenQASM 2.0 code for the quantum Fourier transform.

    The circuit follows the standard decomposition:
        for i in range(n_qubits):
            h i
            for j in range(i+1, n_qubits):
                cp(π/2^(j-i)) j,i   # control j, target i
        if include_swaps: apply bit-reversal swaps.

    Returns a string that can be written to a .qasm file.
    """
    lines = [
        "// Quantum Fourier Transform generated by the Butterfly Compiler",
        "OPENQASM 2.0;",
        'include "qelib1.inc";',
        f"qreg q[{n_qubits}];",
        f"creg c[{n_qubits}];",
        "",
    ]

    # Apply Hadamard and controlled-phase gates
    for i in range(n_qubits):
        lines.append(f"h q[{i}];")
        for j in range(i + 1, n_qubits):
            # Phase angle: 2π / 2^(j-i+1) = π / 2^(j-i)
            angle = np.pi / (2 ** (j - i))
            lines.append(f"cp({angle}) q[{j}],q[{i}];")

    # Bit-reversal swaps if requested
    if include_swaps:
        for i in range(n_qubits // 2):
            j = n_qubits - 1 - i
            if i != j:
                lines.append(f"swap q[{i}],q[{j}];")

    return "\n".join(lines)


def _u3_params(U: np.ndarray, tol: float = DEFAULT_TOL) -> tuple[float, float, float]:
    """
    Extract U3 parameters (θ, φ, λ) from a 2×2 unitary matrix.

    Returns (theta, phi, lam) such that U = exp(iα) * U3(theta, phi, lam)
    for some global phase α.
    """
    a, b, c, d = U[0, 0], U[0, 1], U[1, 0], U[1, 1]

    abs_a = abs(a)
    abs_b = abs(b)
    # Guard against both near-zero (identity up to phase)
    if abs_a < tol and abs_b < tol:
        return 0.0, 0.0, 0.0
    # Compute θ ∈ [0, π] with numerical guard
    theta = 2 * np.arctan2(abs_b, max(abs_a, tol))
    if abs(theta) < tol:
        phi = 0.0
        lam = np.angle(d) - np.angle(a)
    elif abs(theta - np.pi) < tol:
        phi = np.angle(c)
        lam = np.angle(-b)
    else:
        phi = np.angle(c) - np.angle(a)
        lam = np.angle(-b) - np.angle(a)

    return theta, phi, lam


def export_unitary_seed_qasm(
    seed: np.ndarray, n_qubits: int = 1, fmt: str = "qasm"
) -> str:
    """
    Export a unitary seed as a quantum circuit.

    For a 2×2 unitary seed, decompose into standard single‑qubit gates
    (U3 rotation). For larger seeds (qudits), raise NotImplementedError.

    Parameters
    ----------
    seed : np.ndarray
        Unitary matrix (must be square, dimensions 2^k).
    n_qubits : int
        Number of times to apply the Kronecker power (default 1).
    fmt : str
        Output format; currently only "qasm" is supported.

    Returns
    -------
    str
        OpenQASM 2.0 circuit.
    """
    seed = np.asarray(seed)
    if seed.ndim != 2 or seed.shape[0] != seed.shape[1]:
        raise ValueError(f"seed must be square; got shape {seed.shape}")

    tol = DEFAULT_TOL
    if fmt != "qasm":
        raise NotImplementedError(f"Unsupported format: {fmt}")
    if not np.allclose(seed @ seed.conj().T, np.eye(seed.shape[0]), atol=tol):
        raise ValueError("seed must be unitary")

    d = seed.shape[0]
    if d == 2:
        # Get U3 parameters
        theta, phi, lam = _u3_params(seed, tol=tol)

        # Generate QASM for repeated application
        lines = [
            f"// Unitary seed {seed.shape} generated by the Butterfly Compiler",
            "OPENQASM 2.0;",
            'include "qelib1.inc";',
            f"qreg q[{n_qubits}];",
            f"creg c[{n_qubits}];",
            "",
        ]
        lines.extend(
            f"u3({theta},{phi},{lam}) q[{qubit}];" for qubit in range(n_qubits)
        )
        return "\n".join(lines)
    else:
        # For d > 2: handle both power‑of‑two (multi‑qubit) and non‑power‑of‑two (qudit)
        is_power_of_two = (d & (d - 1)) == 0
        if is_power_of_two:
            k = int(np.log2(d))  # d is power of two, log2 exact
            effective_d = d
            effective_seed = seed
            gate_name = f"seed_{d}"
            comment_prefix = f"{k}-qubit"
        else:
            # Qudit case: embed d×d unitary into next power‑of‑two dimension
            k = int(np.ceil(np.log2(d)))
            effective_d = 1 << k  # 2^k
            # Embed seed into larger unitary: U' = diag(U, I)
            effective_seed = np.eye(effective_d, dtype=complex)
            effective_seed[:d, :d] = seed
            gate_name = f"qudit_{d}_to_{effective_d}"
            comment_prefix = f"qudit (d={d}) embedded in {k} qubits"
        # Each seed acts on k qubits, total qubits = n_qubits * k
        total_qubits = n_qubits * k

        lines = [
            f"// Unitary seed {seed.shape} generated by the Butterfly Compiler",
            f"// {comment_prefix} unitary matrix",
            "OPENQASM 2.0;",
            'include "qelib1.inc";',
            f"qreg q[{total_qubits}];",
            f"creg c[{total_qubits}];",
            "",
            f"// Opaque gate definition for {comment_prefix} unitary matrix",
            f"opaque {gate_name}",
        ]
        # Add qubit arguments to gate definition
        if k == 1:
            lines[-1] += " q0;"
        else:
            qubit_args = ", ".join(f"q{i}" for i in range(k))
            lines[-1] += f" {qubit_args};"
        lines.append("")
        # Add matrix as comment (for reference)
        lines.append(f"// Matrix (d={d}, rows ordered lexicographically):")
        for i in range(d):
            row = []
            for j in range(d):
                re = seed[i, j].real
                im = seed[i, j].imag
                if abs(im) < tol:
                    row.append(f"{re:+.6f}")
                elif abs(re) < tol:
                    row.append(f"{im:+.6f}j")
                else:
                    row.append(f"{re:+.6f}{im:+.6f}j")
            lines.append("//   " + " ".join(row))
        if not is_power_of_two:
            lines.append(
                f"// Note: Qudit unitary embedded in {effective_d}×{effective_d} matrix"
            )
            lines.append(f"//       (identity on dimensions {d}..{effective_d - 1})")
        lines.append("")
        # Instantiate the gate n_qubits times on disjoint qubit sets
        for block in range(n_qubits):
            if k == 1:
                lines.append(f"{gate_name} q[{block}];")
            else:
                qubit_list = ", ".join(f"q[{block * k + i}]" for i in range(k))
                lines.append(f"{gate_name} {qubit_list};")
        return "\n".join(lines)


__all__ = [
    "export_qft_qasm",
    "export_unitary_seed_qasm",
]
