"""
Solvability analysis via Lie‑algebra derived series.

Implements `solvability_series` to decide whether a seed matrix generates a
solvable Lie algebra (Beth’s theorem), which guarantees existence of an
O(N log N) butterfly algorithm.
"""

from __future__ import annotations

import numpy as np
from numpy.linalg import svd

from .config import DEFAULT_TOL


def _basis_of_span(vectors: list[np.ndarray], tol: float) -> list[np.ndarray]:
    """Orthonormal basis of span via modified Gram–Schmidt."""
    basis: list[np.ndarray] = []
    for v in vectors:
        v = np.asarray(v, dtype=complex).copy()
        for b in basis:
            v = v - np.vdot(b, v) * b
        nrm = np.linalg.norm(v)
        if nrm > tol:
            basis.append(v / nrm)
    return basis


def lie_closure(
    generators: list[np.ndarray],
    tol: float = 1e-10,
    max_iter: int = 100,
) -> list[np.ndarray]:
    """
    Smallest Lie subalgebra of gl(d) containing the generators.
    Iterate: span := span ∪ {[A,B] : A,B ∈ span} until stable.
    Returns a list of d×d matrices forming an orthonormal basis (vectorized).
    """
    if not generators:
        return []
    d = generators[0].shape[0]
    current = _basis_of_span([M.astype(complex).ravel() for M in generators], tol)
    for _ in range(max_iter):
        new_vecs = list(current)
        for i in range(len(current)):
            Ai = current[i].reshape(d, d)
            for j in range(i + 1, len(current)):
                Aj = current[j].reshape(d, d)
                new_vecs.append((Ai @ Aj - Aj @ Ai).ravel())
        new_basis = _basis_of_span(new_vecs, tol)
        if len(new_basis) == len(current):
            return current  # closed
        current = new_basis
    import warnings

    warnings.warn(
        "lie_closure did not converge within max_iter; returning current basis",
        stacklevel=2,
    )
    return current


def _adjoint_matrix(S):
    """
    Return matrix L such that L @ vec_row(X) = vec_row(S @ X - X @ S).
    """
    d = S.shape[0]
    eye = np.eye(d)
    # Correct formula for row-major vectorization
    return np.kron(S, eye) - np.kron(eye, S.T)


def _lie_closure_adjoint(generators, tol=1e-12, max_iter=20):
    """
    Compute Lie algebra generated by matrices using adjoint representation.
    Returns list of basis matrices.
    """
    if not generators:
        return []
    d = generators[0].shape[0]
    n = d * d
    # Vectorize generators (row-major)
    vecs = [G.ravel() for G in generators]
    B = np.column_stack(vecs)  # n x m
    # Precompute adjoint matrices
    adj_mats = [_adjoint_matrix(G) for G in generators]

    dim_old = 0
    for _ in range(max_iter):
        if B.shape[1] == dim_old:
            break
        dim_old = B.shape[1]
        # Apply each adjoint to current basis
        for adj in adj_mats:
            new = adj @ B  # n x k
            B = np.column_stack([B, new])
        # Orthogonalize and remove dependent columns
        Q, R = np.linalg.qr(B, mode="reduced")
        diag = np.abs(np.diag(R))
        rank = np.sum(diag > tol)
        B = Q[:, :rank]
        if rank >= n:
            break
    # Convert back to matrices
    return [B[:, i].reshape(d, d) for i in range(B.shape[1])]


def _derived_subalgebra_dim(basis, tol=1e-12):
    """
    Dimension of subspace spanned by brackets of basis matrices.
    """
    if len(basis) <= 1:
        return 0

    brackets = [A @ B - B @ A for i, A in enumerate(basis) for B in basis[i + 1 :]]
    if not brackets:
        return 0
    # Vectorize brackets
    vecs = np.array([b.ravel() for b in brackets])
    # Orthogonalize
    _, s, _ = svd(vecs, full_matrices=False)
    return int(np.sum(s > tol))


def _derived_algebra_ce(basis, tol=1e-10, max_iter=5, random_seed=None):
    """
    Compute basis of derived algebra [g,g] via Chevalley–Eilenberg randomized method.

    Parameters
    ----------
    basis : list of (d,d) ndarray
        Orthonormal basis matrices of Lie algebra g.
    tol : float
        Numerical tolerance for rank detection.
    max_iter : int
        Maximum number of random sampling iterations.

    Returns
    -------
    list of (d,d) ndarray
        Orthonormal basis matrices of derived algebra [g,g].
    """
    if len(basis) <= 1:
        return []

    m = len(basis)
    d = basis[0].shape[0]
    rng = np.random.default_rng(random_seed)
    derived_basis = []

    for _ in range(max_iter):
        # Stack basis matrices for batched operations
        basis_stacked = np.stack(basis)  # (m, d, d)

        # Generate random coefficients for left and right combinations
        coeffs_left = rng.normal(size=(m, m)).astype(complex)  # (m, m)
        coeffs_right = rng.normal(size=(m, m)).astype(complex)  # (m, m)

        # Form random matrices X_i = sum_k coeffs_left[i,k] * basis[k]
        # and Y_i = sum_k coeffs_right[i,k] * basis[k]
        X = np.einsum("ik,kab->iab", coeffs_left, basis_stacked)  # (m, d, d)
        Y = np.einsum("ik,kab->iab", coeffs_right, basis_stacked)  # (m, d, d)

        # Compute batched commutators Z_i = X_i @ Y_i - Y_i @ X_i
        XY = np.einsum("iab,ibc->iac", X, Y)  # (m, d, d)
        YX = np.einsum("iab,ibc->iac", Y, X)  # (m, d, d)
        Z = XY - YX  # (m, d, d)

        # Orthonormalize all Z matrices and add to derived basis
        # Vectorize each Z_i and orthogonalize against current derived_basis
        for i in range(m):
            z_vec = Z[i].ravel()
            # Orthogonalize against existing derived basis vectors
            for b_vec in derived_basis:
                proj = np.vdot(b_vec, z_vec)
                z_vec = z_vec - proj * b_vec
            norm = np.linalg.norm(z_vec)
            if norm > tol:
                derived_basis.append(z_vec / norm)

        # Early exit if we've likely captured full derived algebra
        # (dimension cannot exceed m*(m-1)/2)
        max_possible_dim = m * (m - 1) // 2
        if len(derived_basis) >= max_possible_dim:
            break

    # Convert vectorized basis back to matrices
    return [vec.reshape(d, d) for vec in derived_basis]


def _solvability_series_adjoint(
    S, max_depth=20, tol=DEFAULT_TOL, include_adjoint=False
):
    """
    Adjoint representation based solvability series.
    """
    d = S.shape[0]
    generators = [S]
    if include_adjoint:
        generators.append(S.conj().T)
        generators.append(S @ S.conj().T - S.conj().T @ S)

    # Compute Lie algebra via adjoint closure
    g_basis = _lie_closure_adjoint(generators, tol=tol)
    series_dims = [len(g_basis)]

    for step in range(max_depth):
        if len(g_basis) == 0:
            break
        dim_next = _derived_subalgebra_dim(g_basis, tol=tol)
        series_dims.append(dim_next)
        if dim_next == 0:
            break
        if dim_next == len(g_basis):
            return {
                "series": series_dims,
                "is_solvable": False,
                "depth": step + 1,
                "conclusion": f"NOT SOLVABLE (perfect subalgebra at dim {dim_next})",
                "method": "adjoint",
            }
        # Compute basis for derived subalgebra (by recomputing brackets and orthogonalizing)
        brackets = [
            A @ B - B @ A for i, A in enumerate(g_basis) for B in g_basis[i + 1 :]
        ]
        if not brackets:
            break
        # Compute new basis via SVD
        vecs = np.array([b.ravel() for b in brackets])
        _, s, Vh = svd(vecs, full_matrices=False)
        rank = int(np.sum(s > tol))
        g_basis = [Vh[i].reshape(d, d) for i in range(rank)]

    is_solvable = series_dims[-1] == 0
    return {
        "series": series_dims,
        "is_solvable": is_solvable,
        "depth": len(series_dims) - 1,
        "conclusion": (
            "SOLVABLE → butterfly compiles"
            if is_solvable
            else "NOT SOLVABLE (did not terminate in max_depth)"
        ),
        "method": "adjoint",
    }


def _is_nilpotent_power(S: np.ndarray, tol: float) -> bool:
    """Check nilpotency by repeated multiplication (more stable than np.poly)."""
    d = S.shape[0]
    S_k = S.copy()
    for _ in range(d):
        if np.all(np.abs(S_k) < tol):
            return True
        S_k = S_k @ S
    return False


def solvability_series(
    S: np.ndarray,
    max_depth: int = 20,
    tol: float = DEFAULT_TOL,
    include_adjoint: bool = False,
    method: str = "svd",
    random_seed: int | None = None,
) -> dict:
    """
    Compute the derived series of the Lie algebra generated by S (and
    optionally S†). Returns a dict with solvability verdict.

    Parameters
    ----------
    S : np.ndarray
        Seed matrix (d×d).
    max_depth : int, default=20
        Maximum depth of derived series.
    tol : float, default=DEFAULT_TOL
        Numerical tolerance for rank detection.
    include_adjoint : bool, default=False
        Whether to include S† in the generated Lie algebra.
    method : str, default='svd'
        Algorithm for basis orthogonalization: 'svd' (robust), 'incremental'
        (faster for larger d), 'adjoint' (adjoint representation, fastest),
        or 'chevalley' (Chevalley-Eilenberg randomized method, O(d⁵)).

    Mathematical note
    -----------------
    Beth's theorem concerns ⟨S⟩_Lie generated by S alone, NOT ⟨S, S†⟩.
    Including the adjoint turns many solvable examples (Borel, Jordan blocks)
    into gl_n, which is NOT solvable. Default is include_adjoint=False.
    Use include_adjoint=True only for the *-algebra closure.

    Fast structural paths
    ---------------------
    - Strictly upper/lower triangular → nilpotent → solvable
    - Upper/lower triangular (Borel)  → solvable
    - Any nilpotent matrix (all eigenvalues zero) → solvable (dimension 1)
    """
    S = np.asarray(S, dtype=complex)
    d = S.shape[0]

    def bracket(A, B):
        return A @ B - B @ A

    def is_upper_tri(M):
        return np.all(np.abs(np.tril(M, -1)) < tol)

    def is_lower_tri(M):
        return np.all(np.abs(np.triu(M, 1)) < tol)

    def is_strictly_tri(M):
        return (is_upper_tri(M) and np.all(np.abs(np.diag(M)) < tol)) or (
            is_lower_tri(M) and np.all(np.abs(np.diag(M)) < tol)
        )

    def orth_basis(matrices):
        """Orthonormal Frobenius basis for span of `matrices` via SVD."""
        if not matrices:
            return []
        vecs = np.array([M.ravel() for M in matrices])
        _, s, Vh = svd(vecs, full_matrices=False)
        rank = int(np.sum(s > tol))
        return [Vh[i].reshape(d, d) for i in range(rank)]

    # Incremental basis class for method='incremental'
    class IncrementalBasis:
        def __init__(self):
            self.Q = np.zeros((d * d, 0), dtype=complex)  # orthonormal columns
            self.mats = []  # corresponding matrices

        def add_matrix(self, M):
            v = M.ravel()
            w = v.copy()
            # Modified Gram-Schmidt
            for q in self.Q.T:
                w -= q * (q.conj().dot(w))
            norm = np.linalg.norm(w)
            if norm > tol:
                q_new = w / norm
                self.Q = np.column_stack([self.Q, q_new])
                self.mats.append(M)
                return True
            return False

        def add_matrices(self, matrices):
            added = False
            for M in matrices:
                if self.add_matrix(M):
                    added = True
            return added

        def dimension(self):
            return self.Q.shape[1]

        def get_basis_matrices(self):
            return self.mats

    def orth_basis_incremental(matrices):
        """Orthonormal basis using incremental Gram-Schmidt."""
        if not matrices:
            return []
        basis = IncrementalBasis()
        basis.add_matrices(matrices)
        return basis.get_basis_matrices()

    def lie_closure_incremental(generators):
        """Lie closure using incremental basis."""
        basis = IncrementalBasis()
        basis.add_matrices(generators)
        for _ in range(2 * d * d):
            k = basis.dimension()
            if k == 0:
                break
            mats = basis.get_basis_matrices()
            brackets = [
                bracket(mats[i], mats[j]) for i in range(k) for j in range(i + 1, k)
            ]
            if not brackets:
                break
            if not basis.add_matrices(brackets):
                break
        return basis.get_basis_matrices()

    # ── fast structural paths (only valid when generators = {S} alone) ───────
    # If include_adjoint=True, S† may make the algebra non-solvable even when S
    # is triangular (e.g. ⟨Z, Z†⟩ ≅ gl_2), so skip the shortcut.
    if not include_adjoint:
        if is_strictly_tri(S):
            return {
                "series": [d * (d - 1) // 2, 0],
                "is_solvable": True,
                "depth": 1,
                "conclusion": "NILPOTENT (strictly triangular) → solvable",
                "method": "structural",
            }
        if is_upper_tri(S) or is_lower_tri(S):
            return {
                "series": [d * (d + 1) // 2, d * (d - 1) // 2, 0],
                "is_solvable": True,
                "depth": 2,
                "conclusion": "BOREL (triangular) → solvable",
                "diagonal": np.diag(S).tolist(),
                "method": "structural",
            }
        # General nilpotent matrices (all eigenvalues zero)
        if _is_nilpotent_power(S, tol):
            return {
                "series": [1, 0],
                "is_solvable": True,
                "depth": 1,
                "conclusion": "NILPOTENT (all eigenvalues zero) → solvable",
                "method": "nilpotent",
            }

    # ── general derived-series computation ──────────────────────────────────
    generators = [S]
    if include_adjoint:
        generators.append(S.conj().T)
        generators.append(bracket(S, S.conj().T))

    if method == "incremental":
        # Use incremental algorithm
        g_mats = lie_closure_incremental(generators)
        series_dims = [len(g_mats)]
        g_basis = IncrementalBasis()
        g_basis.add_matrices(g_mats)
        for step in range(max_depth):
            if g_basis.dimension() == 0:
                break
            # Compute brackets of current basis
            mats = g_basis.get_basis_matrices()
            k = len(mats)
            brackets = [
                bracket(mats[i], mats[j]) for i in range(k) for j in range(i + 1, k)
            ]
            # Create new basis for derived algebra
            derived_basis = IncrementalBasis()
            derived_basis.add_matrices(brackets)
            dim_next = derived_basis.dimension()
            series_dims.append(dim_next)
            if dim_next == 0:
                break
            if dim_next == g_basis.dimension():
                return {
                    "series": series_dims,
                    "is_solvable": False,
                    "depth": step + 1,
                    "conclusion": f"NOT SOLVABLE (perfect subalgebra at dim {dim_next})",
                    "method": "incremental",
                }
            g_basis = derived_basis
        is_solvable = series_dims[-1] == 0
        return {
            "series": series_dims,
            "is_solvable": is_solvable,
            "depth": len(series_dims) - 1,
            "conclusion": (
                "SOLVABLE → butterfly compiles"
                if is_solvable
                else "NOT SOLVABLE (did not terminate in max_depth)"
            ),
            "method": "incremental",
        }
    elif method == "adjoint":
        result = _solvability_series_adjoint(
            S, max_depth=max_depth, tol=tol, include_adjoint=include_adjoint
        )
        result["method"] = "adjoint"
        return result
    elif method == "chevalley":
        # Chevalley-Eilenberg randomized method for derived series
        # Compute Lie closure using standard algorithm
        g_basis_vec = lie_closure(generators, tol=tol)
        series_dims = [len(g_basis_vec)]
        # Convert to matrix basis for CE algorithm
        g_basis = [v.reshape(d, d) for v in g_basis_vec]

        for step in range(max_depth):
            if len(g_basis) == 0:
                break
            # Compute derived algebra via CE method
            derived_basis = _derived_algebra_ce(
                g_basis, tol=tol, random_seed=random_seed
            )
            dim_next = len(derived_basis)
            series_dims.append(dim_next)
            if dim_next == 0:
                break
            if dim_next == len(g_basis):
                return {
                    "series": series_dims,
                    "is_solvable": False,
                    "depth": step + 1,
                    "conclusion": f"NOT SOLVABLE (perfect subalgebra at dim {dim_next})",
                    "method": "chevalley",
                }
            g_basis = derived_basis

        is_solvable = series_dims[-1] == 0
        return {
            "series": series_dims,
            "is_solvable": is_solvable,
            "depth": len(series_dims) - 1,
            "conclusion": (
                "SOLVABLE → butterfly compiles"
                if is_solvable
                else "NOT SOLVABLE (did not terminate in max_depth)"
            ),
            "method": "chevalley",
        }
    else:  # svd
        # Original SVD-based algorithm
        def lie_closure_svd(basis):
            """Enlarge basis under bracket until stable (= generated Lie algebra)."""
            basis = list(basis)
            for _ in range(2 * d * d):  # dim(gl_n) = d², safe bound
                new_brackets = [
                    bracket(A, B) for i, A in enumerate(basis) for B in basis[i + 1 :]
                ]
                candidate = orth_basis(basis + new_brackets)
                if len(candidate) == len(basis):
                    return candidate
                basis = candidate
            return basis

        g = lie_closure_svd(orth_basis(generators))
        series_dims = [len(g)]

        for step in range(max_depth):
            if len(g) == 0:
                break
            brackets = [bracket(A, B) for i, A in enumerate(g) for B in g[i + 1 :]]
            g_next = orth_basis(brackets)
            series_dims.append(len(g_next))
            if len(g_next) == 0:
                break
            if len(g_next) == len(g):
                return {
                    "series": series_dims,
                    "is_solvable": False,
                    "depth": step + 1,
                    "conclusion": f"NOT SOLVABLE (perfect subalgebra at dim {len(g_next)})",
                    "method": "derived series",
                }
            g = g_next

        is_solvable = series_dims[-1] == 0
        return {
            "series": series_dims,
            "is_solvable": is_solvable,
            "depth": len(series_dims) - 1,
            "conclusion": (
                "SOLVABLE → butterfly compiles"
                if is_solvable
                else "NOT SOLVABLE (did not terminate in max_depth)"
            ),
            "method": "derived series",
        }


def print_solvability(S: np.ndarray, name: str = "S") -> None:
    """
    Pretty‑print the solvability analysis of seed S.

    Parameters
    ----------
    S : np.ndarray
        Square seed matrix.
    name : str, optional
        Label for the seed in the output.
    """
    res = solvability_series(S)
    w = 52
    print(f"\n{'─' * w}\n Supersolvability check: {name}\n{'─' * w}")
    print(f" Lie algebra dim: {res.get('lie_algebra_dim', res['series'][0])}")
    print(f" Derived series dims: {res['series']}")
    print(f" Depth: {res['depth']}")
    print(f" → {res['conclusion']}\n{'─' * w}")


__all__ = ["solvability_series", "print_solvability", "lie_closure"]
